# windsorcli.yaml
name: 'Windsor CLI Action'
description: 'Installs and configures the Windsor CLI for use in GitHub Actions'

inputs:
  version:
    description: 'The version of Windsor CLI to install'
    required: false
    default: v0.5.6
  ref:
    description: 'Git reference to build Windsor CLI from source'
    required: false
    default: ""
  context:
    description: 'The context to use for Windsor CLI commands'
    required: false
    default: "local"
  workdir:
    description: 'The working directory for Windsor CLI commands'
    required: false
    default: ""
  verbose:
    description: 'Enable verbose logging'
    required: false
    default: "false"

runs:
  using: 'composite'
  steps:

    - name: Check if Git is installed
      id: check-git
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const { execSync } = require('child_process');
          const verbose = '${{ inputs.verbose }}' === 'true';
          try {
            const output = execSync('git --version', { encoding: 'utf-8' });
            if (verbose) console.log('Git version:', output.trim());
          } catch (error) {
            console.error('Git is not installed. Please install Git to proceed.');
            process.exit(1);
          }

    - name: Check Go Installation
      if: ${{ inputs.ref != '' }}
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const { execSync } = require('child_process');
          const os = require('os');
          const verbose = '${{ inputs.verbose }}' === 'true';

          try {
            const platform = os.platform();
            let goPathCommand = platform === 'win32' ? 'where go' : 'which go';
            const goPath = execSync(goPathCommand, { encoding: 'utf-8' }).trim();
            if (verbose) console.log('Go binary path:', goPath);
            
            const goVersion = execSync('go version', { encoding: 'utf-8' }).trim();
            if (verbose) console.log('Go version:', goVersion);
          } catch (error) {
            console.error('Go is not installed or not found in PATH');
            process.exit(1);
          }

    - name: Install Windsor CLI
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const { execSync } = require('child_process');
          const fs = require('fs');
          const path = require('path');
          const os = require('os');
          
          const cleanInput = (input) => typeof input === 'string' ? input.replace(/\r?\n|\r/g, '') : input;
          const verbose = '${{ inputs.verbose }}' === 'true';

          const isWindows = os.platform() === 'win32';
          const installFolder = path.resolve(process.env.GITHUB_WORKSPACE, 'bin');
          const windsorExecutable = isWindows ? 'windsor.exe' : 'windsor';
          const githubWorkspace = process.env.GITHUB_WORKSPACE;
          let version = cleanInput('${{ inputs.version }}');
          const ref = cleanInput('${{ inputs.ref }}');
          const input_context = cleanInput('${{ inputs.context }}');
          let rawWorkdir = cleanInput('${{ inputs.workdir }}');
          
          if (verbose) {
            console.log('Installation parameters:');
            console.log('- Version:', version);
            console.log('- Ref:', ref);
            console.log('- Context:', input_context);
            console.log('- Workdir:', rawWorkdir);
            console.log('- Install folder:', installFolder);
          }
          
          let workdir;
          if (rawWorkdir) {
            const workspacePath = process.env.GITHUB_WORKSPACE || githubWorkspace;
            const platformPath = rawWorkdir.replace(/\//g, path.sep);
            
            if (process.platform === 'win32') {
              const cleanPath = platformPath.replace(/^[A-Za-z]:[^\\]/, '');
              workdir = path.join(workspacePath, cleanPath);
            } else {
              if (path.isAbsolute(platformPath)) {
                workdir = platformPath;
              } else {
                workdir = path.join(workspacePath, platformPath);
              }
            }
            if (verbose) console.log('Resolved workdir:', workdir);
          } else {
            workdir = process.cwd();
          }

          const execCommand = (command) => {
            try {
              if (verbose) console.log('Executing:', command);
              execSync(command, { stdio: 'inherit' });
            } catch (error) {
              console.error(`Error executing command: ${command}`);
              if (verbose) console.error('Error details:', error.message);
              process.exit(1);
            }
          };

          if (!fs.existsSync(path.join(installFolder, windsorExecutable))) {
            const arch = process.arch === 'arm64' ? 'arm64' : 'amd64';
            const osType = isWindows ? 'windows' : process.platform === 'darwin' ? 'darwin' : 'linux';

            if (ref) {
              if (verbose) console.log(`Installing Windsor CLI from ref: ${ref}`);
              execCommand(`git clone https://github.com/windsorcli/cli.git ${githubWorkspace}/cli`);
              execCommand(`cd ${githubWorkspace}/cli && git pull && git checkout ${ref}`);
              execCommand(`cd ${githubWorkspace}/cli/cmd/windsor && go build -o ${path.join(installFolder, windsorExecutable)}`);
              version = 'vdev';
            } else {
              const numericVersion = version.replace(/^v/, '');
              const localFileName = `windsor_${numericVersion}_${osType}_${arch}.tar.gz`;
              const downloadUrl = `https://github.com/windsorcli/cli/releases/download/${version}/${localFileName}`;

              if (verbose) console.log('Downloading Windsor CLI:', downloadUrl);

              const curlCommand = `curl -L -o ${localFileName} ${downloadUrl}`;
              const mkdirCommand = isWindows ? `if not exist "${installFolder}" mkdir "${installFolder}"` : `mkdir -p "${installFolder}"`;
              const extractCommand = isWindows 
                ? `powershell -Command "tar -xzf ${localFileName} -C ${installFolder}"`
                : `tar -xzf ${localFileName} -C "${installFolder}"`;
              const chmodCommand = isWindows 
                ? `icacls "${path.join(installFolder, windsorExecutable)}" /grant Everyone:F`
                : `chmod +x "${path.join(installFolder, windsorExecutable)}"`;
              const rmCommand = isWindows ? `del ${localFileName}` : `rm -rf ${localFileName}`;

              try {
                execCommand(curlCommand);
                execCommand(mkdirCommand);
                execCommand(extractCommand);
                execCommand(chmodCommand);
                execCommand(rmCommand);
              } catch (error) {
                console.error('Error executing commands');
                if (verbose) console.error('Error details:', error.message);
                process.exit(1);
              }

              let installedVersionOutput = execSync(`${path.join(installFolder, windsorExecutable)} version`).toString().trim();
              let installedVersionMatch = installedVersionOutput.match(/^Version:\s*(\S+)/);
              let installedVersion = installedVersionMatch ? `v${installedVersionMatch[1]}` : '';

              if (verbose) {
                console.log('Version check:');
                console.log('- Expected:', version);
                console.log('- Installed:', installedVersion);
              }

              if (installedVersion !== version) {
                console.error(`Version mismatch: expected ${version}, got ${installedVersion}`);
                process.exit(1);
              }
            }
          }

          fs.appendFileSync(process.env.GITHUB_PATH, `${installFolder}\n`);
          if (verbose) console.log('Added to PATH:', installFolder);

          if (workdir && fs.existsSync(workdir)) {
            process.chdir(workdir);
            if (verbose) console.log('Changed to workdir:', workdir);
          } else if (workdir) {
            console.error(`Workdir does not exist`);
            process.exit(1);
          }

    - name: Set Windsor CLI environment variables
      uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
      with:
        script: |
          const { execSync } = require('child_process');
          const fs = require('fs');
          const path = require('path');
          const os = require('os');

          const isWindows = os.platform() === 'win32';
          const installFolder = path.resolve(process.env.GITHUB_WORKSPACE, 'bin');
          const windsorExecutable = isWindows ? 'windsor.exe' : 'windsor';
          const githubEnv = process.env.GITHUB_ENV;
          const input_context = '${{ inputs.context }}';
          const workdir = '${{ inputs.workdir }}';
          const verbose = '${{ inputs.verbose }}' === 'true';

          if (verbose) {
            console.log('Environment setup:');
            console.log('- Install folder:', installFolder);
            console.log('- Context:', input_context);
            console.log('- Workdir:', workdir);
            console.log('- Current directory:', process.cwd());
          }

          if (!process.env.PATH.includes(installFolder)) {
            console.error('Install folder not in PATH');
            process.exit(1);
          }

          if (input_context) {
            try {
              const command = `${windsorExecutable} init ${input_context}${verbose ? ' --verbose' : ''}`;
              if (verbose) console.log('Running:', command);
              const { stdout, stderr } = execSync(command, { 
                encoding: 'utf-8',
                stdio: ['pipe', 'pipe', 'pipe']
              });
              if (verbose) {
                if (stdout) console.log('Init stdout:', stdout);
                if (stderr) console.log('Init stderr:', stderr);
              }
              
              const defaultContextDir = path.join(process.cwd(), 'contexts', input_context);
              if (verbose) console.log('Checking context directory:', defaultContextDir);
              if (!fs.existsSync(defaultContextDir)) {
                throw new Error('Context directory not created');
              }
              
              const contextOutput = execSync(`${windsorExecutable} context get${verbose ? ' --verbose' : ''}`, { 
                encoding: 'utf-8',
                stdio: 'pipe'
              });
              if (verbose) console.log('Context output:', contextOutput.trim());
              if (contextOutput.trim() !== input_context) {
                throw new Error('Context not set correctly');
              }
            } catch (error) {
              console.error('Error setting Windsor context');
              if (verbose) console.error('Error details:', error.message);
              process.exit(1);
            }
          }

          if (workdir) {
            try {
              process.chdir(workdir);
              if (verbose) console.log('Changed to workdir:', workdir);
            } catch (error) {
              console.error('Error changing to workdir');
              if (verbose) console.error('Error details:', error.message);
              process.exit(1);
            }
          }

          // Run windsor env to get environment variables
          try {
            if (verbose) console.log(`Running: ${windsorExecutable} env`);
            const envOutput = execSync(`${windsorExecutable} env`, { 
              encoding: 'utf-8',
              stdio: 'pipe'
            });

            if (verbose) console.log('Raw windsor env output:', envOutput);

            if (!envOutput) {
              throw new Error('windsor env returned no output');
            }

            const envLines = envOutput.split('\n')
              .filter(line => line.trim() && !line.startsWith('#') && !line.includes('Cannot execute commands'));

            if (verbose) console.log('Processed environment lines:', envLines);

            // Process each environment variable
            envLines.forEach(line => {
              if (line.startsWith('export ')) {
                // Handle bash-style export
                const assignment = line.replace(/^export /, '');
                // Split only on the first '='
                const eqIdx = assignment.indexOf('=');
                if (eqIdx !== -1) {
                  const key = assignment.slice(0, eqIdx);
                  let value = assignment.slice(eqIdx + 1);
                  // Remove quotes from value
                  const cleanValue = value.replace(/^["']|["']$/g, '');
                  // Use the proper GitHub Actions environment variable format
                  const envLine = `${key}<<EOF\n${cleanValue}\nEOF\n`;
                  if (verbose) console.log(`Setting environment variable: ${key}`);
                  fs.appendFileSync(githubEnv, envLine);
                }
              } else if (line.startsWith('$env:')) {
                // Handle PowerShell-style
                const match = line.match(/^\$env:([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/);
                if (match) {
                  const [_, key, rawValue] = match;
                  // For Windows, ensure proper quote handling
                  let value = rawValue.trim();
                  
                  // If the value starts with -var-file= or similar, ensure proper quoting
                  if (value.includes('-var-file=') || value.includes('-backend-config=')) {
                    const parts = value.split('=');
                    const flag = parts[0];
                    const path = parts[1];
                    if (path.startsWith('"') && !path.endsWith('"')) {
                      value = `${flag}=${path}"`;
                    }
                  }
                  
                  // Use the proper GitHub Actions environment variable format
                  const envLine = `${key}<<EOF\n${value}\nEOF\n`;
                  if (verbose) console.log(`Setting environment variable: ${key}`);
                  fs.appendFileSync(githubEnv, envLine);
                }
              }
            });

            // Verify the variables were set
            const setVars = envLines.map(line => {
              if (line.startsWith('export ')) {
                return line.replace(/^export /, '').split('=')[0];
              } else if (line.startsWith('$env:')) {
                return line.match(/^\$env:([A-Za-z_][A-Za-z0-9_]*)/)[1];
              }
              return null;
            }).filter(Boolean);

            if (verbose) console.log('Set environment variables:', setVars.join(', '));
          } catch (error) {
            console.error('Error running windsor env');
            if (verbose) console.error('Error details:', error.message);
            process.exit(1);
          }
