# windsorcli.yaml
name: 'Windsor CLI Action'

inputs:
  version:
    required: false
    type: string
    default: v0.5.2
  ref:
    required: false
    type: string
    default: ""
  install_folder:
    required: false
    type: string
    default: ${{ github.workspace }}/bin
  context:
    required: false
    type: string
    default: ""
  workdir:
    required: false
    type: string
    default: ${{ github.workspace }}

runs:
  using: 'composite'
  steps:

    - name: Install Git (Windows)
      if: runner.os == 'Windows'
      uses: actions/github-script@v7
      with:
        script: |
          const { execSync } = require('child_process');
          const fs = require('fs');
          const path = require('path');

          try {
            console.log('Checking if Git is installed...');
            execSync('git --version', { stdio: 'inherit' });
            console.log('Git is already installed.');
          } catch (error) {
            console.log('Git is not installed. Installing Git manually...');
            const gitInstaller = 'Git-2.33.0-64-bit.exe'; // Update to the latest version as needed
            const gitDownloadUrl = `https://github.com/git-for-windows/git/releases/download/v2.33.0.windows.1/${gitInstaller}`;
            const downloadCommand = `Invoke-WebRequest -Uri ${gitDownloadUrl} -OutFile ${gitInstaller}`;
            const installCommand = `Start-Process -FilePath .\\${gitInstaller} -ArgumentList '/VERYSILENT', '/NORESTART' -Wait`;

            execSync(downloadCommand, { shell: 'powershell.exe', stdio: 'inherit' });
            execSync(installCommand, { shell: 'powershell.exe', stdio: 'inherit' });
            console.log('Git installed successfully.');
          }

    - name: Install Windsor CLI
      uses: actions/github-script@v7
      with:
        script: |
          const { execSync } = require('child_process');
          const fs = require('fs');
          const path = require('path');
          const os = require('os');

          const installFolder = path.resolve('${{ inputs.install_folder }}');
          const workdir = path.resolve('${{ inputs.workdir }}');
          let version = '${{ inputs.version }}';
          const ref = '${{ inputs.ref }}';
          const input_context = '${{ inputs.context }}';

          const isWindows = os.platform() === 'win32';
          const windsorExecutable = isWindows ? 'windsor.exe' : 'windsor';

          const execCommand = (command) => {
            try {
              console.log(`Executing: ${command}`);
              execSync(command, { stdio: 'inherit' });
            } catch (error) {
              console.error(`Error executing command: ${command}`);
              console.error(error.message);
              process.exit(1);
            }
          };

          console.log(`Install folder: ${installFolder}`);
          console.log(`Workdir: ${workdir}`);

          if (!fs.existsSync(path.join(installFolder, windsorExecutable))) {
            console.log('Windsor CLI not found, proceeding with installation.');

            const arch = process.arch === 'arm64' ? 'arm64' : 'amd64';
            const osType = isWindows ? 'windows' : process.platform === 'darwin' ? 'darwin' : 'linux';

            if (ref) {
              console.log(`Installing Windsor CLI from ref (${ref})...`);
              execCommand(`git clone https://github.com/windsorcli/cli.git`);
              execCommand(`cd cli && git checkout ${ref}`);
              execCommand(`cd cli/cmd/windsor && go build -o ${path.join(installFolder, windsorExecutable)}`);
              version = 'vdev';  // Set expected version to vdev when building from source
            } else {
              const numericVersion = version.replace(/^v/, '');
              const localFileName = `windsor_${numericVersion}_${osType}_${arch}.tar.gz`;
              const downloadUrl = `https://github.com/windsorcli/cli/releases/download/${version}/${localFileName}`;

              const curlCommand = `curl -L -o ${localFileName} ${downloadUrl}`;
              const mkdirCommand = `mkdir -p "${installFolder}"`;
              const extractCommand = isWindows 
                ? `7z x ${localFileName} -so | 7z x -aoa -si -ttar -o"${installFolder}"`
                : `tar -xzf ${localFileName} -C "${installFolder}"`;
              const chmodCommand = isWindows 
                ? `icacls "${path.join(installFolder, windsorExecutable)}" /grant Everyone:F`
                : `chmod +x "${path.join(installFolder, windsorExecutable)}"`;
              const rmCommand = isWindows ? `del ${localFileName}` : `rm -rf ${localFileName}`;

              try {
                execCommand(curlCommand);
                execCommand(mkdirCommand);
                execCommand(extractCommand);
                execCommand(chmodCommand);
                execCommand(rmCommand);
              } catch (error) {
                console.error('Error executing commands:', error.message);
                process.exit(1);
              }

              let installedVersionOutput = execSync(`${path.join(installFolder, windsorExecutable)} version`).toString().trim();

              // Extract the version number from the output
              let installedVersionMatch = installedVersionOutput.match(/^Version:\s*(\S+)/);
              let installedVersion = installedVersionMatch ? `v${installedVersionMatch[1]}` : '';

              console.log(`Expected version: "${version}"`);
              console.log(`Installed version: "${installedVersion}"`);

              if (installedVersion !== version) {
                console.error(`Version mismatch: expected ${version}, got ${installedVersion}`);
                process.exit(1);
              } else {
                console.log(`Installed version: ${installedVersion}`);
              }

              console.log('Windsor CLI installation complete.');
            }

            console.log(`Setting environment variables for Windsor CLI.`);
            fs.appendFileSync(process.env.GITHUB_PATH, `${installFolder}\n`);
            fs.appendFileSync(process.env.GITHUB_ENV, `WINDSOR_PROJECT_ROOT=${workdir}\n`);

            // Set the environment variable in the current process
            process.env.WINDSOR_PROJECT_ROOT = workdir;

            console.log(`workdir=${workdir}`);
            console.log(`WINDSOR_PROJECT_ROOT value: ${process.env.WINDSOR_PROJECT_ROOT}`);

            if (input_context !== "") {
              console.log(`Setting context to ${input_context}`);
              execCommand(`cd ${workdir} && ${path.join(installFolder, windsorExecutable)} init ${input_context}`);
            }
          }
